name: progistack_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_map: ^3.1.0
  permission_handler: ^10.2.0
  location: ^4.4.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  flutter_map_marker_cluster: ^1.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

